### ISSUE TITLE
Blocking a lot of false positives

### ISSUE THREAD

**Issue by p1r473** [Jigsaw88/Spotify-Ad-List#2]
@Jigsaw88 Blocking a lot of false positives
Did you even test spotify? Theres no way you can play Spotify with all this blocked. 
See for reference: https://gist.github.com/mrprobot/257f3af652c0b4599634c7c063ec2d88

accounts.spotify.com - obviously for accounts
api-partner.spotify.com - partner api, like chromecast
ap.spotify.com - access point (load balancer), links to ap.gslb.spotify.com
audio-fa.scdn.co                            # audio used by chromecast, links to beta.spotify.map.fastly.net
cast.scdn.co                                # interface used by chromecast (partner devices), links to beta.spotify.map.fastly.net
developer.spotify.com                       # developer portal, links to developer.spotify.map.fastly.net
embed.spotify.com - spotify embedded
guc-spclient.spotify.com #Spotify redirector usa (san jose) links to 7.127.154.104.bc.googleusercontent.com and sjc.weblb-wg.dual-gslb.spotify.com
i.scdn.co #Spotify Album Covers
open.scdn.co                                # cdn equivalent of open.spotify.com, links to beta.spotify.map.fastly.net
play.spotify.com - ...
play.spotify.edgekey.net ...
scdnco.spotify.map.fastly.net #Required
seektables.scdn.co #Spotify patented search of multimedia segments (fetching), links to beta.spotify.map.fastly.net

**Comment by Jigsaw88** [comment]
Thanks for the list, i removed all of these from the list + some other domains which are obv needed for Spotify to work correctly.
When i still used this i never had issues playing music.

Sorry for responding so late.
